name: Artifact Excersice

on:
  push:
    branches:
      - "main"
env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v3
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .